# Generated by Django 3.0.5 on 2020-04-29 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_post_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(default='NULL', upload_to='profile_pics'),
        ),
    ]
