# Generated by Django 3.0.5 on 2020-04-30 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '__first__'),
        ('journal', '0004_post_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='group_to_post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='groups.LinkGroup'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(default='webcamVideo.webm', upload_to='profile_pics'),
        ),
    ]
