# Generated by Django 3.0.5 on 2020-04-30 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '__first__'),
        ('journal', '0005_auto_20200430_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='group_to_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.LinkGroup'),
        ),
    ]
