# Generated by Django 3.0.5 on 2020-04-30 02:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '__first__'),
        ('journal', '0005_auto_20200429_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='group_to_post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='groups.LinkGroup'),
            preserve_default=False,
        ),
    ]
