# Generated by Django 3.0.5 on 2020-04-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_auto_20200430_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(default='webcamVideo (9).webm', upload_to='profile_pics'),
        ),
    ]
