# Generated by Django 3.0.5 on 2020-04-09 17:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journal', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=200)),
                ('group_description', models.CharField(default='New Group!', max_length=2000)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('bkey', models.BinaryField()),
                ('group_avatar', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('members', models.ManyToManyField(to='users.Profile')),
                ('posts', models.ManyToManyField(to='journal.Post')),
            ],
        ),
    ]
