# Generated by Django 3.0.5 on 2020-04-30 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '__first__'),
        ('users', '0003_auto_20200430_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_group_for_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='single_group', to='groups.LinkGroup'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='groups',
            field=models.ManyToManyField(related_name='all_groups', to='groups.LinkGroup'),
        ),
    ]
