version: "3"
services:
  mongo:
    container_name: mongoDB
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  restify:
    container_name: restifyApp
    restart: always
    build: ./
    ports:
      - "8080:8080"
    volumes:
      - ./server:/usr/src/server
    links:
      - mongo
