# Generated by Django 3.0.5 on 2020-04-29 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_auto_20200409_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(default='/media/webcamVideo.webm', upload_to='profile_pics'),
        ),
    ]
